//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendScan_x64.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"ftp://pafiuser:Tr3ndM!cr0@ftp-download.trendmicro.com/pafi_patterns/root/trendmicro.zip,ftp://pafiuser:Tr3ndM!cr0@ftp-download.trendmicro.com/pafi_patterns/root/trend_icrc.zip,ftp://pafiuser:Tr3ndM!cr0@ftp-download.trendmicro.com/pafi_patterns/root/trend_hfopr.zip")]
        public string PatternURIs {
            get {
                return ((string)(this["PatternURIs"]));
            }
            set {
                this["PatternURIs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vscanamd64.exe")]
        public string VscanName {
            get {
                return ((string)(this["VscanName"]));
            }
            set {
                this["VscanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ScanInterval {
            get {
                return ((int)(this["ScanInterval"]));
            }
            set {
                this["ScanInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vsapi64.dll")]
        public string VscanEngine {
            get {
                return ((string)(this["VscanEngine"]));
            }
            set {
                this["VscanEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ScanLevel {
            get {
                return ((int)(this["ScanLevel"]));
            }
            set {
                this["ScanLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14400,3600,300")]
        public string UpdateInterval {
            get {
                return ((string)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"osce10,http://osce106-p.activeupdate.trendmicro.com/activeupdate;housecall72,http://housecall7-ssa-p.activeupdate.trendmicro.com/activeupdate;osce10_china,http://osce106-p.activeupdate.trendmicro.com.cn/activeupdate/china;tmconsumer,http://tis16-p.pre-opr-au.trendmicro.com/activeupdate")]
        public string AUURLs {
            get {
                return ((string)(this["AUURLs"]));
            }
            set {
                this["AUURLs"] = value;
            }
        }
    }
}
